In [4]:
import matplotlib
matplotlib.use('Qt5Agg')
import sys
import numpy as np

## dataset

In [5]:
sys.path  
sys.path = ['/snap/pycharm-professional/346/plugins/python/helpers/pydev',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/snap/pycharm-professional/346/plugins/python/helpers/third_party/thriftpy',
 '/snap/pycharm-professional/346/plugins/python/helpers/pydev',
 '/snap/pycharm-professional/346/plugins/python/helpers/pycharm_display',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python38.zip',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/lib-dynload',
 '/home/tom/.local/lib/python3.8/site-packages',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/site-packages',
 '/home/tom/Bureau/phd/simulation/sim-fish',
 '/home/tom/Bureau/phd/simulation/ssam-release',
 '/home/tom/pysmFISH',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/site-packages/SimpleITK-2.0.0rc2.dev910+ga138e-py3.8-linux-x86_64.egg',
 '/snap/pycharm-professional/346/plugins/python/helpers/pycharm_matplotlib_backend',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/site-packages/IPython/extensions',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg']
sys.path

['/snap/pycharm-professional/346/plugins/python/helpers/pydev',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/home/tom/Bureau/phd/simulation/ComSeg_pkg/code/',
 '/snap/pycharm-professional/346/plugins/python/helpers/third_party/thriftpy',
 '/snap/pycharm-professional/346/plugins/python/helpers/pydev',
 '/snap/pycharm-professional/346/plugins/python/helpers/pycharm_display',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python38.zip',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/lib-dynload',
 '/home/tom/.local/lib/python3.8/site-packages',
 '/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/site-packages',
 '/home/tom/Bureau/phd/simulation/sim-fish',
 '/home/tom/Bureau/phd/simulation/ssam-release

# dataset initialization

In [6]:
import comseg
from comseg import dataset
import importlib
importlib.reload(dataset)

<module 'comseg.dataset' from '/home/tom/Bureau/phd/simulation/ComSeg_pkg/comseg/dataset.py'>

In [7]:
#selected_genes = ['Atp6v0d2', 'Abcg1','Rtkn2',  'Igfbp2','Sftpc','Cxcl15','Cd79a','Ms4a2', 'Fcer1a',
 #                    'Ccdc153','Scgb3a2', 'Scgb1a1', 'Cst3','Cdh5', 'Clec14a','Inmt', 
  #                   'Pcolce2','C1qc', 'C1qa', 'C1qb','Upk3b','Ifitm6','Plac8','Ms4a4b', 'Ccl5', 'Hcst',
   #                  'Gzma', 'Ncr1','S100a9','Mmrn1', 'Acta2','Myh11', 'Cd3g', 'Cd3d']
    

selected_genes = ['Atp6v0d2', 'Abcg1','Rtkn2',  'Igfbp2','Cxcl15','Cd79a','Ms4a2', 'Fcer1a']
 #                    'Ccdc153','Scgb3a2', 'Scgb1a1', 'Cst3','Cdh5', 'Clec14a','Inmt', ]
  #                   'Pcolce2','C1qc', 'C1qa', 'C1qb','Upk3b','Ifitm6','Plac8','Ms4a4b', 'Ccl5', 'Hcst',
   #                  'Gzma', 'Ncr1','S100a9','Mmrn1', 'Acta2','Myh11', 'Cd3g', 'Cd3d']

dataset = comseg.dataset.ComSegDataset(selected_genes = selected_genes,
    path_dataset_folder = "/media/tom/T7/simulation/test_set/small_df",
                path_to_mask_prior = "/media/tom/T7/simulation/test_set/mask")
dataset.add_prior_from_mask()

add 07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_004
add 07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_006
add prior to 07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_004
add prior to 07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_006


In [8]:

dataset.compute_in_situ_edge(dico_scale={"x": 0.103, 'y': 0.103, "z": 0.3},  # in micrometer
        images_subset = None,
        mode="nearest_nn_radius",
        n_neighbors=25,
        radius=1,  # in micormeter
        distance="pearson",
        per_images=False,
        sampling=False,
        sampling_size=100000)

image name :  07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_004
8
image name :  07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_006
8


  0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                             | 0/8 [00:00<?, ?it/s]/home/tom/anaconda3/envs/bigfish38_samm/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4068: PearsonRConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(PearsonRConstantInputWarning())
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

({'Atp6v0d2': {'Atp6v0d2': 0.9999999999999997,
   'Abcg1': 0.15164403520356773,
   'Rtkn2': -1,
   'Igfbp2': -0.01612556734139533,
   'Cxcl15': -0.2659602854445551,
   'Cd79a': -0.07055864924649877,
   'Ms4a2': -0.011812089612327758,
   'Fcer1a': -1},
  'Abcg1': {'Atp6v0d2': 0.15164403520356773,
   'Abcg1': 1.0,
   'Rtkn2': -1,
   'Igfbp2': -0.020588466983030882,
   'Cxcl15': -0.32797896636884044,
   'Cd79a': -0.08713270181960298,
   'Ms4a2': -0.01508119446809924,
   'Fcer1a': -1},
  'Rtkn2': {'Atp6v0d2': -1,
   'Abcg1': -1,
   'Rtkn2': -1,
   'Igfbp2': -1,
   'Cxcl15': -1,
   'Cd79a': -1,
   'Ms4a2': -1,
   'Fcer1a': -1},
  'Igfbp2': {'Atp6v0d2': -0.01612556734139533,
   'Abcg1': -0.020588466983030882,
   'Rtkn2': -1,
   'Igfbp2': 0.9999999999999863,
   'Cxcl15': -0.08055884477810255,
   'Cd79a': -0.023459531667047624,
   'Ms4a2': -0.003577858596421585,
   'Fcer1a': -1},
  'Cxcl15': {'Atp6v0d2': -0.2659602854445551,
   'Abcg1': -0.32797896636884044,
   'Rtkn2': -1,
   'Igfbp2': -0.080

In [9]:
np.unique(dataset[1].prior)

array([  0,   1,   2,   3,   4,  13,  15,  17,  22,  25,  38,  40,  42,
        44,  46,  48,  49,  56,  58,  63,  64,  66,  67,  70,  71,  74,
        76,  80,  81,  83,  84,  91,  95, 105, 107, 111, 114])

In [10]:
for i in dataset:
    print(i)

07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_004
07_CtrlNI_Pdgfra-Cy3_Serpine1-Cy5_006


In [11]:
import comseg

from comseg import model
import importlib
importlib.reload(comseg)
importlib.reload(model)

from comseg import model


In [12]:

dict_anndata_img = {}
for img_name  in dataset:
    comseg_m = model.ComSeg(selected_genes = dataset.selected_genes,
        df_spots_label = dataset[img_name],
                 dict_scale={"x": 0.103, 'y': 0.103, "z": 0.3})
    comseg_m.create_graph(dict_co_expression=dataset.dict_co_expression ,
                         )
    comseg_m.community_vector(
                             clustering_method="louvain_with_prior",
                             weights_name="weight",

                             prior_keys="prior",
                             seed=None,
                             super_node_prior_keys="prior",
                             confidence_level=1,
                             # param for multigrpah leiden
                             )
    comseg_m.community_anndata.obs["img_name"]  = img_name
    dict_anndata_img[img_name] = comseg_m.community_anndata

computing knn
adding edges


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84684/84684 [00:01<00:00, 68944.85it/s]


creation of  super node with prior
1
2649
479
205
90
39
25
8
11
3
3
8

problem of convergence to check in my method

True
320
1
89
11
231
1
12
1
219
1
219


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3346/3346 [00:00<00:00, 10516.14it/s]


computing knn
adding edges


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 76822/76822 [00:01<00:00, 69489.23it/s]


creation of  super node with prior
1
2369
421
164
73
57
18
6
11
23

problem of convergence to check in my method

True
293
1
84
16
209
1
15
2
194
1
3
191
1
191


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3086/3086 [00:00<00:00, 10882.89it/s]


In [13]:
import anndata as ad 
ad.concat([ dict_anndata_img[img_name] for img_name in dict_anndata_img], merge="same").X


Observation names are not unique. To make them unique, call `.obs_names_make_unique`.


<410x8 sparse matrix of type '<class 'numpy.float32'>'
	with 916 stored elements in Compressed Sparse Row format>

In [56]:
comseg_m.community_anndata.X[[True] *191 ,:]


<191x8 sparse matrix of type '<class 'numpy.float32'>'
	with 356 stored elements in Compressed Sparse Row format>

In [15]:
np.nonzero(np.sum(comseg_m.community_anndata.X[: ,[True] *8 ], axis=1) > 0)[0]

array([  0,   1,   2,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  32,  33,  34,  35,  36,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 18

In [42]:
len(comseg_m.community_anndata)

192

In [54]:
anndata.X[0].toarray()

array([[0.        , 1.1297495 , 0.        , 0.        , 0.        ,
        0.05540636, 0.        , 0.        ]], dtype=float32)

In [55]:
np.zeros(comseg_m.community_anndata.X.shape)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
import comseg

from comseg import clustering
import importlib
importlib.reload(comseg)
importlib.reload(clustering)
from comseg import clustering




In [75]:
insitu_clustering  = clustering.InSituClustering(dict_anndata_img = dict_anndata_img,
                                                 selected_genes = dataset.selected_genes)

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.


In [76]:
norm_expression_vectors, param_sctransform = insitu_clustering.compute_normalization_parameters( )

shape count matrix (401, 6)
Index(['0', '1', '2', '3', '4', '5'], dtype='object')
Writing temporary files...
Running scTransform via Rscript...
Reading output files...
Clipping residuals...


In [67]:
np.array(comseg_m.community_anndata.obs['nb_rna'] > 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [83]:
bool_index  = np.array(insitu_clustering.anndata.obs['nb_rna']) > 3
insitu_clustering.anndata[bool_index, :]

View of AnnData object with n_obs × n_vars = 75 × 8
    obs: 'list_coord', 'node_index', 'prior', 'index_commu', 'nb_rna', 'img_name'
    var: 'features'

In [87]:
insitu_clustering.anndata.X.toarray()

array([[0.0000000e+00, 1.1297495e+00, 0.0000000e+00, ..., 5.5406358e-02,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 4.5577738e-01, 0.0000000e+00, ..., 5.0105676e-08,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 2.6442729e-06, 0.0000000e+00, ..., 6.4084427e-03,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.5218295e-02,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.6646077e-04,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)